### ISSUE TITLE
Change BrokeredComponent1 class name?

### ISSUE THREAD

**Issue by ammoman** [lancecontreras/BCTemplates#1]
I tried renaming BrokeredComponent1 class to something else, for example just BrokeredComp.  For that to work I also update the Package.appmanifest ActivatableClass record to the new name.  With these changes it compiled and instantiated the class, but as soon as I called GetValue(), it threw the exception:

Unable to cast object of type 'Server.BrokeredComp' to type 'Server.IBrokeredCompClass'

I also tried adding additional classes in the Server project and added those classes to the Client's Package.appmanifest, but I ran into the same exception - I can instantiate the new class, but calling any methods on it shows the same cast exception.

Is there something else that needs to be updated to rename the brokered component class or to add additional classes to the server?

**Comment by lancecontreras** [comment]
Try to make sure that the icacls and the regsvr32 command ran on the directory where your proxy.dll is. If you check the pre-build event of the project, I think I have the commands in the prebuild event  but you may want to change the path if you're using a different one. With this, you need to run visual studio as an administrator. 

Or you can manually run it, open command prompt as an administrator, go to the place where your proxy.dll is, the execute the following: 

icacls . /T /grant "ALL APPLICATION PACKAGES":RX

AND 

regsvr32 Proxy.dll

**Comment by ammoman** [comment]
Thanks for the tip - I wasn't running VS as the admin after the change, but the build wasn't showing any errors with the pre-build event so I thought the registration was working correctly.

Running as admin allowed the proxy DLL to be registered correctly so  had access to the renamed class.

Thanks for the help!
